server:
  listen_host: "0.0.0.0"
  listen_port: 8080
  webhook_path: "/webhook"

webclient:
  timeout: 3
  max_retries: 1
  retry_delay: 1       # in seconds

permata_bank_login:
  permata_static_key: "WAP000e331ccc768a4da883b80DW0035"
  api_key: "a3550b7b-fb89-472a-b6c8-6d4ae4a543f5"

  # token_url: "https://api.pbdevtest.com/apiservice/oauth/token"
  token_url: "https://webhook.site/14899f0f-d6fb-4562-b2b3-3d2f2a8a3b07"
  username: "2bc21968-3188-4682-94be-668416cf2166"
  password: "5792acf1-d05e-4e5b-b33a-3a9101d5cc9f"
  login_payload: "grant_type=client_credentials"

permata_bank_webhook:
  # callbackstatus_url: "https://api.pbdevtest.com/apiservice/wa/callbackstatus" 
  callbackstatus_url: "https://webhook.site/7b1dd642-cdfc-4c21-a159-581f203d448f" 
  organizationname: "WD62876003"

token_scheduler:
  periodic_interval_mins: 3          # Run scheduler every 15 minutes

telegram_alert:
  api_url: "https://api.telegram.org/bot5801394322:AAEaWtt-jGFb81sT7KqrUOw1Pg9m9dtkWas/sendMessage"
  chat_id: "-1002522258027"
  message_thread_id: "2"
  alert_message_prefix: "[Webhook Gateway Alert]"

logger:
  dir: log/                    
  file_name: webhook-gateway
  max_backups: 0                            # set 0 for unlimited backups
  max_size: 10                              # in mb
  max_age: 90                               # in days, set 0 for unlimited days
  compress: true
  local_time: true